version: '3.8'
services:

  reverse-proxy:
    restart: always
    image: traefik:v2.9
    ports:
      # The HTTP port
      - "80:80"
      - "443:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8085:8085"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./docker/traefik/certs:/tools/certs:ro

  webserver:
    build: docker/general
    container_name: ubuntu.${APP_NAMESPACE}
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT:-8000}:80'
      - '${NGINX_HTTP_PORT:-8001}:443'
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.web-https.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.web-https.tls=true
  mariadb:
    image: 'mariadb:10'
    container_name: mariadb.${APP_NAMESPACE}
    ports:
      - '${FORWARD_DB_PORT:-}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-laravel}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/mariadb/data:/var/lib/mysql'
    networks:
      - web
      - default
    labels:
      - traefik.enable=false
  redis:
    image: redis
    container_name: redis.${APP_NAMESPACE}
    volumes:
      - ./docker/redis/data:/data
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    networks:
      - default
    labels:
      - traefik.enable=false

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST:-mariadb}
      - UPLOAD_LIMIT=1G
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(phpmyadmin.loc)

networks:
  web:
    name: traefik_default
    external: true
